RCE: Add typescript checking pre-commit hook
- Adds support for packages/ to have their own pre-commit hooks.
- Adds a pre-commit-hook to the RCE that checks typescript

Fixes MAT-1290

flag=none
qa-risk=low

test plan:

- change a typescript file in canvas, stage, commit
  - ensure that tsc is run in the root of canvas, but not in the rce
- change a typescript file in packages/canvas-rce, stage, commit
  - ensure that tsc is run in packages/canvas-rce, but not in the root
- make a commit without changing typescript anywhere:
  - ensure no tsc is run

Change-Id: I997818a84bdcdac1d5e03680fc91d0a94a630b6e
Reviewed-on: https://gerrit.instructure.com/c/canvas-lms/+/314023
Reviewed-by: Ed Schiebel <eschiebel@instructure.com>
QA-Review: Ed Schiebel <eschiebel@instructure.com>
Tested-by: Service Cloud Jenkins <svc.cloudjenkins@instructure.com>
Product-Review: Yona Appletree <yona.appletree@instructure.com>

diff --git a/hooks/pre-commit b/hooks/pre-commit
--- a/hooks/pre-commit
+++ b/hooks/pre-commit
@@ -11,8 +11,8 @@ SCRIPTPATH="$(
 CANVAS=$(dirname $SCRIPTPATH)
 
 if [ $(pwd -P) = $CANVAS ]; then
-  # if .ts or .tsx files have changed, run tsc
-  if git diff --cached --name-only | grep -qE '\.(ts|tsx)$'; then
+  # if .ts or .tsx files have changed (excluding those in packages/), run tsc
+  if git diff --cached --name-only | grep -vE '^packages/' | grep -qE '\.(ts|tsx)$'; then
     if [ -f node_modules/.bin/tsc ]; then
       echo 'Checking TypeScript...'
       node_modules/.bin/tsc -p tsconfig.json --noEmit
@@ -40,6 +40,21 @@ if [ $(pwd -P) = $CANVAS ]; then
     docker-compose exec -T web yarn run lint:staged ||
       echo "You should run yarn locally or check to make sure docker is running."
   fi
+
+  # per-package pre-commit hooks
+  git diff --cached --name-only | grep -E -o '^(packages/[^/]+)' | sort | uniq | while read -r PACKAGE; do
+    # check if CHANGED_PACKAGES/pre-commit-hook.sh exists and run it
+    if [ -f "$PACKAGE/pre-commit-hook.sh" ]; then
+      echo "Running pre-commit hook for $PACKAGE"
+
+      (cd "$PACKAGE" && "./pre-commit-hook.sh")
+
+      if [ $? -ne 0 ]; then
+        echo "Pre-commit hook for $PACKAGE failed, aborting commit"
+        exit 1
+      fi
+    fi
+  done || exit 1
 fi
 
 $CANVAS/script/rlint ${RLINT_ARGUMENTS:- --auto-correct-all}
